export const TASKVISIBLE = "TASKVISIBLE";
export const TASKINFO = "TASKINFO";
export const UPDATETASKVISIBLE = "UPDATETASKVISIBLE";
export const SENDINFOMODAL = "SENDINFOMODAL";
export const TASKOWNER = "TASKOWNER";