export const GET_TASK_FILTER = 'GET_TASK_FILTER';
export const SET_DO_VISIBLE = 'SET_DO_VISIBLE';
export const SET_DOING_VISIBLE = 'SET_DOING_VISIBLE';
export const SET_ANALYZE_VISIBLE = 'SET_ANALYZE_VISIBLE';
export const SET_STOPPED_VISIBLE = 'SET_STOPPED_VISIBLE';
export const SET_BLOCKED_VISIBLE = 'SET_BLOCKED_VISIBLE';
export const SET_DONE_VISIBLE = 'SET_DONE_VISIBLE';
export const SET_CANCELED_VISIBLE = 'SET_CANCELED_VISIBLE';