export const WEB_SOCKET_STATE= 'WEB_SOCKET_STATE';
export const WEB_SOCKET_MESSAGE= 'WEB_SOCKET_MESSAGE';
export const GET_WEB_SOCKET= 'GET_WEB_SOCKET';
export const GET_WEB_SOCKET_HISTORIC= 'GET_WEB_SOCKET_HISTORIC';
export const GET_USERS_ONLINE = 'GET_USERS_ONLINE';
export const ADD_USERS_ONLINE = "ADD_USERS_ONLINE";
export const REMOVE_USERS_ONLINE = "REMOVE_USERS_ONLINE";
export const REMOVE_USERS_LIST = "REMOVE_USERS_LIST";