export const SET_ORDER = 'SET_ORDER';
export const SET_COL = 'SET_COL';
export const SET_STATE_VISIBLE = "SET_STATE_VISIBLE";
export const SET_PRIORITY_VISIBLE = "SET_PRIORITY_VISIBLE";
export const SET_VINC_VISIBLE = "SET_VINC_VISIBLE";
export const SET_DATE_VISIBLE = "SET_DATE_VISIBLE";
export const SET_COMPANY_VISIBLE = "SET_COMPANY_VISIBLE";